import { CarsType } from '../../../server/src/models/cars.model';
export const category = [
    'Sedan',
    'Hatch Back',
    'Pickup Truck',
    'Spyder',
    'Pony Car',
    'SUV',
    'Coupe',
    'Convertible',
    'Minivan',
    'Station Wagon',
    'Truck',
    'Jeep',
    'Hot Hatch',
    'Crossover/CUV',
    'Sports sedan',
    'Sports Cars',
    'Electric Car',
    'Limousine',
    'Military vehicle',
    'UTE',
    'Dragster',
]

export const specificationArray: (keyof CarsType)[] = [
    "width",
    "height",
    "length",
    "wheelBase",
    "groundClearance",
    "kerbWeight",
    "bootSpace",
    "seatingCapacity",
    "door",
    "engineType",
    "cylinders",
    "displacement",
    "horsePower",
    "torque",
    "fuelSystem",
    "turboCharger",
    "cylinderConfiguration",
    "valvesPerCylinder",
    "valueMechanism",
    "compressionRatio",
    "driveTrain",
    "maxSpeed",
    "transmissionType",
    "gearBox",
    "steeringType",
    "minimumTurningRadius",
    "powerAssisted",
    "frontSuspension",
    "rearSuspension",
    "frontBrake",
    "rearBrake",
    "tyreSize",
    "wheelType",
    "wheelSize",
    "pcd",
    "spareTyreSize",
    "mileageCity",
    "mileageHighway",
    "fuelTankCapacity",
]